### ISSUE TITLE
Get an error that it cant find a bunch of posix directories

### ISSUE THREAD

**Issue by charlieb-xyz** [fbriere/mpv-scripts#1]
`[tree_profiles] Lua error: /home/cha/.config/mpv/scripts/tree-profiles.lua:235: module 'posix' not found:
[tree_profiles] 	no field package.preload['posix']
[tree_profiles] 	no file '/usr/local/share/lua/5.2/posix.lua'
[tree_profiles] 	no file '/usr/local/share/lua/5.2/posix/init.lua'
[tree_profiles] 	no file '/usr/local/lib/lua/5.2/posix.lua'
[tree_profiles] 	no file '/usr/local/lib/lua/5.2/posix/init.lua'
[tree_profiles] 	no file '/usr/share/lua/5.2/posix.lua'
[tree_profiles] 	no file '/usr/share/lua/5.2/posix/init.lua'
[tree_profiles] 	no file './posix.lua'
[tree_profiles] 	no file '/home/cha/.config/mpv/scripts/posix.lua'
[tree_profiles] 	no file '/usr/local/lib/lua/5.2/posix.so'
[tree_profiles] 	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/posix.so'
[tree_profiles] 	no file '/usr/lib/lua/5.2/posix.so'
[tree_profiles] 	no file '/usr/local/lib/lua/5.2/loadall.so'
[tree_profiles] 	no file './posix.so'
`

I installed lua 5.2 and luarocks hoping it would install the necessary dependencies but no luck.

**Comment by fbriere** [comment]
As stated in the documentation, `tree_profiles` currently requires [luaposix](https://github.com/luaposix/luaposix) to be installed.

That said, I had already started working on getting rid of this dependency; I think I should be able to finish the job and upload a new version within the next few days.  Stay tuned!  :smile:

**Comment by charlieb-xyz** [comment]
bitchin, thank you.
